openapi: 3.0.1
info:
  title: checkNin
  description: API Definition of checkNin
  version: 1.0.0
servers:
- url: http://localhost:8290/checknin
paths:
  /:
    get:
      responses:
        default:
          description: Default response
