openapi: 3.0.1
info:
  title: getNationalId
  description: API Definition of getNationalId
  version: 1.0.0
servers:
- url: http://localhost:8290/getnationalid
paths:
  /:
    get:
      responses:
        default:
          description: Default response
