openapi: 3.0.1
info:
  title: testdblookup
  description: API Definition of testdblookup
  version: 1.0.0
servers:
- url: http://localhost:8290/testdblookup
paths:
  /:
    get:
      responses:
        default:
          description: Default response
